#!/bin/sh

#SBATCH -A DBS21007
#SBATCH --job-name=ds002843-mriqc
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds002843-mriqc/.reproman/jobs/local/20220303-111956-449d/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds002843-mriqc/.reproman/jobs/local/20220303-111956-449d/stderr

#SBATCH --nodes=2
#SBATCH --ntasks=9
#SBATCH --time=8:00:00
#SBATCH --partition=small

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds002843-mriqc/.reproman/jobs/local/20220303-111956-449d

module load launcher
module load remora
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 8); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

remora "$LAUNCHER_DIR"/paramrun